on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: "Build APK Android"
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.16.9
      - run: flutter --version
      - run: flutter config --no-analytics
      - run: flutter doctor -v